### ISSUE TITLE
ECDSA support

### ISSUE THREAD

**Issue by Andrew-Lees11** [IBM-Swift/BlueCryptor#50]
In [SwiftJWT](https://github.com/IBM-Swift/Swift-JWT), we would like to support [ES256](https://ldapwiki.com/wiki/ES256). This requires the JWT be signed/verified using ECDSA. BlueCryptor seems like the right place to implement a common API for the Elliptic curve algorithm.

OpenSSL has an implementation that is documented [here](https://www.openssl.org/docs/man1.0.2/crypto/ecdsa.html). This could be used for the linux implementation.

Apple security has an implementation that is documented [here](https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/signing_and_verifying#see-also). This could be used for the iOS/MacOS implementation.

@billabt This approach is fairly similar to [BlueRSA](https://github.com/IBM-Swift/BlueRSA). Is there a reason you made BlueRSA a separate repo instead of incorporating it into BlueCryptor?

**Comment by sglushchenko** [comment]
Same problem.

**Comment by sglushchenko** [comment]
Test file that I take from Apple. I'm' not sure that I should make with it anything. Maybe create a pem file with OpenSSL. But for sending a push notification to APNS need make JWT and sign it with ES256 algorithm. Waiting while it will be added to BlueCryptor. Or I will make it with node.js.

[AuthKey_H99Y4T66A4.p8.zip](https://github.com/IBM-Swift/BlueCryptor/files/2739394/AuthKey_H99Y4T66A4.p8.zip)

**Comment by billabt** [comment]
I'm currently unavailable this week.  However, I'll start looking at it and hopefully start coming up with an implementation plan on Monday.  I don't think it'll take that long.  I may move this _BlueRSA_ rather than here depending on the best way to implement that API.  Offhand, I think it'll end up in _BlueRSA_ since the API that'll be presented will most likely look more like a _BlueRSA_ API.

@Andrew-Lees11 The reason for the separation is twofold.  First, _BlueCryptor_ has been around a lot longer than _BlueRSA_ and I didn't want to _destabilize it_ during development of the RSA APIs.  The second reason is the fact that the API for _BlueRSA_ is significantly _different_ than that presented by _BlueCryptor_ and I felt that it would be best to avoid any confusion for users of the packages.

**Comment by billabt** [comment]
Let me stew on it.  That might work but I think the _style_ of the BlueRSA API is going to be closer to what we need. I think we might be duplicating a bit of code if we create a new repo.

**Comment by Andrew-Lees11** [comment]
I have moved my current prototype to a [branch on BlueRSA](https://github.com/IBM-Swift/BlueRSA/tree/ECDSA). This is currently able to sign and verify on using common crypto from a PEM public and private key. On linux it can sign and verify from a key created by OpenSSL however it is not currently able to parse a PEM file into the required key. 
I am away for the next week but will continue working on this after that.

**Comment by billabt** [comment]
Sounds good to me. Thanks. Enjoy your week away from the office. 😉

**Comment by Andrew-Lees11** [comment]
I'm going to close this issue here since it is unlikely to go in this repo. I have made a working prototype on this [BlueRSA branch](https://github.com/IBM-Swift/BlueRSA/tree/issue.ECDSA). It can sign and verify ES256 JWTs and is working with jwt.io. It still needs tidying up and choosing where we would like to put it.
